# Persistent Volume Claim
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: portfolio-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 1Gi

---
# Deployment Object
apiVersion: apps/v1
kind: Deployment
metadata:
  name: melville-deployment
spec:
  selector:
    matchLabels:
      app: melville
  replicas: 2
  template:
    metadata:
      labels:
        app: melville
    spec:
      containers:
      - name: melville
        image: fleeforezz/melville:1.25-beta
        resources:
          limits:
            cpu: "1000m"
            memory: "1000Mi"
          requests:
            cpu: "500m"
            memory: "750Mi"
        # volumeMounts:
        # - mountPath: "/"
        #   name: portfolio-storage
        ports:
        - containerPort: 8080
      # volumes:
      # - name: portfolio-storage
      #   persistentVolumeClaim:
      #     claimName: portfolio-pvc
      automountServiceAccountToken: false

---

# Service Object
apiVersion: v1
kind: Service
metadata:
  name: melville-service
spec:
  selector:
    app: melville
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32520
